name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag to create/update release for (e.g., v0.1.0)'
        required: false
        type: string

jobs:
  build:
    name: Build Cross-Platform Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - GOOS: windows
            GOARCH: amd64
            OUTPUT_NAME: json-tail-windows-amd64.exe
          - GOOS: darwin
            GOARCH: arm64
            OUTPUT_NAME: json-tail-darwin-arm64
          - GOOS: darwin
            GOARCH: amd64
            OUTPUT_NAME: json-tail-darwin-amd64
          - GOOS: linux
            GOARCH: amd64
            OUTPUT_NAME: json-tail-linux-amd64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build Binary
      env:
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}
      run: |
        go build -v -o "dist/${{ matrix.OUTPUT_NAME }}" .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: dist/
        retention-days: 5
        overwrite: true

  release:
    name: Create/Update Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && inputs.release_tag != '')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: dist
          overwrite: true

      - name: Create/Update Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
          tag_name: ${{ github.event.inputs.release_tag || github.ref_name }}